export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR'


export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


export const LOGIN_PHONE_REQUEST = 'LOGIN_PHONE_REQUEST';
export const LOGIN_PHONE_SUCCESS = 'LOGIN_PHONE_SUCCESS';