export const GET_CITY_LIST = 'GET_CITY_LIST';
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS';
export const GET_CITY_LIST_ERROR = 'GET_CITY_LIST_ERROR';

export const HANDLE_CITY_OPEN = 'HANDLE_CITY_OPEN'
export const HANDLE_CITY_OPEN_SUCCESS = 'HANDLE_CITY_OPEN_SUCCESS'
export const HANDLE_CITY_OPEN_ERROR = 'HANDLE_CITY_OPEN_ERROR'